<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class BattleBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $level;
	public $created_at, $updated_at;
	protected $lazyLoad = true;

	public function __construct(  $id=0  ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "battles";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["level"] = "int";


		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:

}

class BattleControlBase extends MagratheaModelControl {
	protected static $modelName = "Battle";
	protected static $dbTable = "battles";
}
?>