<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class CategoryBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name;
	public $created_at, $updated_at;
	protected $lazyLoad = true;

	public function __construct(  $id=0  ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "categories";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";

		$this->relations["properties"]["Persons"] = null;
		$this->relations["methods"]["Persons"] = "GetPersons";

		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:
	public function GetPersons(){
		$pk = $this->dbPk;
		$this->relations["properties"]["Persons"] = PersonControlBase::GetWhere(array("category_id" => $this->$pk));
		return $this->relations["properties"]["Persons"];
	}

}

class CategoryControlBase extends MagratheaModelControl {
	protected static $modelName = "Category";
	protected static $dbTable = "categories";
}
?>