<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class PersonBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $category_id, $sub_category, $peso;
	public $created_at, $updated_at;
	protected $lazyLoad = true;

	public function __construct(  $id=0  ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "people";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["category_id"] = "int";
		$this->dbValues["sub_category"] = "string";
		$this->dbValues["peso"] = "int";

		$this->relations["properties"]["Category"] = null;
		$this->relations["methods"]["Category"] = "GetCategory";

		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:
	public function GetCategory(){
		$this->relations["properties"]["Category"] = new Category($this->category_id);
		return $this->relations["properties"]["Category"];
	}

}

class PersonControlBase extends MagratheaModelControl {
	protected static $modelName = "Person";
	protected static $dbTable = "people";
}
?>