<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class SettingsBase extends MagratheaModel implements iMagratheaModel {

	public $id, $qtd_battles, $qtd_events, $qtd_people, $active, $version;
	public $created_at, $updated_at;
	protected $lazyLoad = true;

	public function __construct(  $id=0  ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "settings";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["qtd_battles"] = "int";
		$this->dbValues["qtd_events"] = "int";
		$this->dbValues["qtd_people"] = "int";
		$this->dbValues["active"] = "int";
		$this->dbValues["version"] = "float";


		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:

}

class SettingsControlBase extends MagratheaModelControl {
	protected static $modelName = "Settings";
	protected static $dbTable = "settings";
}
?>