<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class MailBase extends MagratheaModel implements iMagratheaModel {

	public $id, $source_id, $email_from, $email_replyTo, $email_to, $msg_subject, $message, $priority, $add_date, $sent_date, $sent_status;
	public $created_at, $updated_at;
	protected $lazyLoad = true;

	public function __construct( $id=0 ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "mail";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["source_id"] = "int";
		$this->dbValues["email_from"] = "string";
		$this->dbAlias["from"] = "email_from";
		$this->dbValues["email_replyTo"] = "string";
		$this->dbAlias["replyTo"] = "email_replyTo";
		$this->dbValues["email_to"] = "string";
		$this->dbAlias["to"] = "email_to";
		$this->dbValues["msg_subject"] = "string";
		$this->dbAlias["subject"] = "msg_subject";
		$this->dbValues["message"] = "text";
		$this->dbValues["priority"] = "int";
		$this->dbValues["add_date"] = "datetime";
		$this->dbValues["sent_date"] = "datetime";
		$this->dbValues["sent_status"] = "int";


		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:

}

class MailControlBase extends MagratheaModelControl {
	protected static $modelName = "Mail";
	protected static $dbTable = "mail";
}
?>