<?php

## FILE GENERATED BY MAGRATHEA.
## SHOULD NOT BE CHANGED MANUALLY

class SourceBase extends MagratheaModel implements iMagratheaModel {

	public $id, $name, $from;
	public $created_at, $updated_at;
	protected $lazyLoad = true;

	public function __construct( $id=0 ){ 
		$this->Start();
		if( !empty($id) ){
			$pk = $this->dbPk;
			$this->$pk = $id;
			$this->GetById($id);
		}
	}
	public function Start(){
		$this->dbTable = "source";
		$this->dbPk = "id";
		$this->dbValues["id"] = "int";
		$this->dbValues["name"] = "string";
		$this->dbValues["from"] = "string";


		$this->dbAlias["created_at"] =  "datetime";
		$this->dbAlias["updated_at"] =  "datetime";
	}

	// >>> relations:

}

class SourceControlBase extends MagratheaModelControl {
	protected static $modelName = "Source";
	protected static $dbTable = "source";
}
?>